# Generated by Django 4.2 on 2025-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=50)),
                ('market_zone', models.CharField(max_length=300)),
                ('market_manager', models.CharField(max_length=50)),
                ('market_number', models.CharField(max_length=50)),
                ('market_opening_date', models.DateField(auto_now_add=True)),
                ('market_employees', models.IntegerField()),
            ],
        ),
    ]
