# Generated by Django 4.2 on 2025-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpartaMarkets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='market_opening_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
