# Generated by Django 4.2 on 2025-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_regdate', models.DateField(auto_now_add=True)),
                ('customer_number', models.CharField(max_length=50)),
            ],
        ),
    ]
