# Generated by Django 4.2 on 2025-02-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_regdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
