# Generated by Django 4.2 on 2025-02-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpartaMarkets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('product_zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='SpartaMarkets.marketmodel')),
            ],
        ),
    ]
